const globalData = {
  companiesData: [
    {
      company: "Go Air",
      companySubName: "Private Limited",
      issueStartDate: "12/12/2024",
      issueEndDate: "15/12/2024",
      issueDate: "12/12/2024",
      issueSize: "3600 Crores",
      priceRange: "50-60",
      minInvestment: "50000",
      qty: "100 Shares/5Lots",
      minimumQuantity: "150 Shares",
      listedOn: "15/12/2024",
      listedPrice: "150",
      listingGains: "10",
      listingPercentage: "10.0%",
    },
    {
      company: "Bajaj Energy",
      companySubName: "Private Limited",
      issueStartDate: "12/12/2024",
      issueEndDate: "15/12/2024",
      issueDate: "12/12/2024",
      issueSize: "3600 Crores",
      priceRange: "50-60",
      minInvestment: "50000",
      qty: "100 Shares/5Lots",
      minimumQuantity: "150 Shares",
      listedOn: "15/12/2024",
      listedPrice: "150",
      listingGains: "10",
      listingPercentage: "10.0%",
    },
    {
      company: "OYO",
      companySubName: "Private Limited",
      issueDate: "12/12/2024",
      issueStartDate: "12/12/2024",
      issueEndDate: "15/12/2024",
      issueSize: "3600 Crores",
      minimumQuantity: "150 Shares",
      priceRange: "50-60",
      minInvestment: "50000",
      qty: "100 Shares/5Lots",
      listedOn: "15/12/2024",
      listedPrice: "150",
      listingGains: "10",
      listingPercentage: "10.0%",
    },
  ],
  columns: [
    "Company/Issue Date",
    "Issue Size",
    "Price Range",
    "Min Invest/Qty",
  ],
  IPO_STEPS: [
    { name: "Bidding starts", value: "12 Dec 2034", isCompleted: true },
    { name: "Bidding ends", value: "15 Dec 2034", isCompleted: true },
    {
      name: "Allotment finalization",
      value: "15 Dec 2034",
      isCompleted: true,
    },
    { name: "Refund initiation", value: "18 Dec 2034", isCompleted: true },
    { name: "Demat transfer", value: "18 Dec 2034", isCompleted: true },
    { name: "Listing date", value: "21 Dec 2034", isCompleted: true },
  ],

  IPO_STEPS_Mobile: [
    { name: "Bidding starts", value: "12 Dec 2034", isCompleted: true },
    { name: "Bidding ends", value: "15 Dec 2034", isCompleted: true },
    {
      name: "Allotment finalization",
      value: "15 Dec 2034",
      isCompleted: true,
    },
    { name: "Refund initiation", value: "18 Dec 2034", isCompleted: true },
    { name: "Demat transfer", value: "18 Dec 2034", isCompleted: true },
    { name: "Listing date", value: "21 Dec 2034", isCompleted: true },
  ],
};

export default globalData;
